language: java
dist: trusty

script: ./gradlew build

jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - bash <(curl -s https://codecov.io/bash)
