FROM openjdk:8-jre-alpine

MAINTAINER Andrei Varabyeu <andrei_varabyeu@epam.com>
LABEL version="@version@"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx512m"
ENV JAVA_EXECUTABLE_JAR=/app.jar

RUN sh -c "echo $'#!/bin/bash\n\
exec \"java $JAVA_OPTS -jar $JAVA_EXECUTABLE_JAR\"' > /start.sh && chmod +x /start.sh"

VOLUME /tmp
ADD build/libs/lib /lib

ADD build/libs/service-authorization-3.0.2-SNAPSHOT.jar /app.jar

RUN sh -c 'touch /app.jar'
EXPOSE 8080

RUN ls -la
RUN cat /start.sh

ENTRYPOINT ["/start.sh"]
