FROM openjdk:8-jre-alpine

MAINTAINER Andrei Varabyeu <andrei_varabyeu@epam.com>
LABEL version="@version@"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx512m"
ENV JAVA_APP=/app.jar

RUN wget -O /start.sh https://raw.githubusercontent.com/reportportal/reportportal/master/scripts/start.sh && \
    chmod +x /start.sh

VOLUME /tmp
ADD build/libs/lib /lib

ADD build/libs/service-authorization-3.0.2-SNAPSHOT.jar /app.jar

RUN sh -c 'touch /app.jar'
EXPOSE 8080

RUN ls -la
RUN cat /start.sh

ENTRYPOINT ["/start.sh"]
