rp:
  db:
    url: jdbc:postgresql://localhost:5432/reportportal?user=rpuser&password=rppass
  uat:
    serviceUrl: http://localhost:8080/uat
server:
  port: 9999
logging:
  level:
    org:
      hibernate:
        SQL: debug