FROM adoptopenjdk:11-jdk-hotspot-bionic as builder

WORKDIR /usr/src/reportportal

COPY gradle/ ./gradle
COPY gradlew .
RUN ./gradlew wrapper

COPY project-properties.gradle build.gradle gradlew settings.gradle gradle.properties ./
RUN ./gradlew resolveDependencies --stacktrace

COPY . ./
RUN ./gradlew build --stacktrace

FROM openjdk:11-jre-slim
LABEL maintainer="Andrei Varabyeu <andrei_varabyeu@epam.com>"

ENV JAVA_OPTS="-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.security.egd=file:/dev/./urandom"
ENV JAVA_APP=/app.jar

RUN echo $'#!/bin/sh \n\
exec java $JAVA_OPTS -jar $JAVA_APP' > /start.sh && chmod +x /start.sh

VOLUME /tmp

COPY --from=builder /usr/src/reportportal/build/libs/service-authorization.jar ./app.jar

RUN sh -c 'touch /app.jar'

EXPOSE 8080

ENTRYPOINT /start.sh