FROM openjdk:8-jre-alpine

MAINTAINER Andrei Varabyeu <andrei_varabyeu@epam.com>
LABEL version="@version@"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx512m"
ENV JAVA_EXECUTABLE_JAR=/app/app.jar

RUN sh -c "echo '#!/bin/bash \n\
exec java $JAVA_OPTS -jar JAVA_EXECUTABLE_JAR' > /start.sh && chmod +x /start.sh"

VOLUME /tmp
ADD lib /lib

ADD @name@-@version@.jar app.jar

RUN sh -c 'touch /app.jar'
EXPOSE 8080

ENTRYPOINT ["start.sh"]
