FROM frolvlad/alpine-oraclejdk8:slim

MAINTAINER Andrei Varabyeu <andrei_varabyeu@epam.com>
LABEL version="${project.version}"
LABEL description="${project.description}"


RUN apk --no-cache add unzip

ENV APP_FILE ${project.name}-${project.version}
ENV APP_DOWNLOAD_URL https://dl.bintray.com/epam/reportportal/com/epam/reportportal/${project.name}/${project.version}/$APP_FILE.zip

VOLUME /tmp
ADD $APP_DOWNLOAD_URL /app/

RUN unzip /app/$APP_FILE.zip -d /app/ && rm -rf /app/$APP_FILE.zip
RUN mv /app/$APP_FILE.jar /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java","-Xmx256m","-Djava.security.egd=file:/dev/./urandom","-jar", "/app/app.jar"]