FROM openjdk:8-jre-alpine

LABEL maintainer "Andrei Varabyeu <andrei_varabyeu@epam.com>"
LABEL version="@version@"
LABEL description="@description@"

RUN apk --no-cache add unzip openssl

ENV APP_FILE @name@-@version@
ENV APP_DOWNLOAD_URL https://dl.bintray.com/epam/reportportal/com/epam/reportportal/@name@/@version@/$APP_FILE.zip
ENV JAVA_OPTS="-Xmx512m -Djava.security.egd=file:/dev/./urandom"
ENV JAVA_EXECUTABLE_JAR=/app/app.jar

RUN sh -c "echo '#!/bin/bash\n\
exec java $JAVA_OPTS -jar JAVA_EXECUTABLE_JAR' > /run.sh && chmod +x /start.sh"

VOLUME /tmp

RUN mkdir /app
RUN wget -O /app/$APP_FILE.zip $APP_DOWNLOAD_URL
RUN unzip /app/$APP_FILE.zip -d /app/ && rm -rf /app/$APP_FILE.zip
RUN mv /app/$APP_FILE.jar JAVA_EXECUTABLE_JAR

EXPOSE 8080
ENTRYPOINT ["/start.sh"]