FROM frolvlad/alpine-oraclejdk8:slim

MAINTAINER Andrei Varabyeu <andrei_varabyeu@epam.com>

VOLUME /tmp
ADD https://dl.bintray.com/epam/reportportal/com/epam/reportportal/${project.name}/${version}/${project.name}-dist-${version}.zip /app

RUN sh -c 'touch /app/${project.name}-${version}.jar'
EXPOSE 8080
ENTRYPOINT ["java","-Xmx256m","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
