FROM openjdk:8-jre

### Set quay.io image cache. Since the build is for development only,
### there is no need to keep them forever
### details: https://support.coreos.com/hc/en-us/articles/115001384693-Tag-Expiration
LABEL quay.expires-after=1w

LABEL maintainer "Andrei Varabyeu <andrei_varabyeu@epam.com>"
LABEL version="@version@"
LABEL description="@description@"

ENV JAVA_OPTS="-Xmx512m -Djava.security.egd=file:/dev/./urandom"
ENV JAVA_APP=/app/app.jar

RUN echo '#!/bin/sh \n\
exec java $JAVA_OPTS -jar $JAVA_APP' > /start.sh && chmod +x /start.sh

VOLUME /tmp

RUN mkdir /app
COPY build/libs/service-authorization.jar /app/app.jar
COPY build/libs/lib/ /app/lib/

EXPOSE 8080
ENTRYPOINT ["/start.sh"]
